version: "3.8"

services:
  cockroachdb:
    image: cockroachdb/cockroach:v23.1.11
    command: start-single-node --insecure
    ports:
      - "26257:26257"  # SQL
      - "8081:8080"    # Web UI
    volumes:
      - cockroach-data:/cockroach/cockroach-data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

volumes:
  cockroach-data:

